### ISSUE TITLE
Production task problem!

### ISSUE THREAD

**Issue by mnemanja** [jakemmarsh/angularjs-gulp-browserify-boilerplate#102]
Related to this. Need help with it ASAP please.

https://github.com/alferov/generator-angular-gulp-browserify/issues/3

**Comment by mnemanja** [comment]
Luckily I found this solution:

    gulp.task('prod', ['clean'], function(cb *= function() {}*) {

So I've moved it below, to be as it was before the ES6 implementation.

cb = cb || = function() {};

This is my first real contact with ES6 so I apologize in advance if my lack of expertise there raises some alarms, and I hope that this helps others not to panic as I did :)

Cheers

**Comment by mnemanja** [comment]
Different issue, but with the same task. This happens on the fresh install.

$ gulp prod
[13:31:36] Requiring external module babel-core/register
[13:31:39] Using gulpfile c:\www\bb\gulpfile.babel.js
[13:31:39] Starting 'clean'...
[13:31:39] Finished 'clean' after 9.91 ms
[13:31:39] Starting 'prod'...
[13:31:39] Starting 'styles'...
[13:31:39] Starting 'images'...
[13:31:39] Starting 'fonts'...
[13:31:39] Starting 'views'...
[13:31:39] Starting 'browserify'...
[13:31:39] Finished 'prod' after 51 ms
[13:31:39] Finished 'fonts' after 45 ms
[13:31:39] Finished 'views' after 140 ms
[13:31:39] Finished 'styles' after 164 ms
[13:31:40] gulp-imagemin: Minified 3 images (saved 53.64 kB - 69.7%)
[13:31:40] Finished 'images' after 1.17 s
[13:31:43] Finished 'browserify' after 4.65 s
[13:31:43] Starting 'gzip'...
[13:31:44] Finished 'gzip' after 204 ms
[13:31:44] 'prod' errored after 4.88 s
[13:31:44] Error: task completion callback called too many times
    at finish (c:\www\bb\node_modules\gulp\node_modules\orchestrator\lib\runTask
.js:15:10)
    at cb (c:\www\bb\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:
29:3)
    at finish (c:\www\bb\node_modules\run-sequence\index.js:38:5)
    at runNextSet (c:\www\bb\node_modules\run-sequence\index.js:66:5)
    at Gulp.onTaskEnd (c:\www\bb\node_modules\run-sequence\index.js:53:5)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (c:\www\bb\node_modules\gulp\node_modules
\orchestrator\index.js:264:8)
    at c:\www\bb\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (c:\www\bb\node_modules\gulp\node_modules\orchestrator\lib\runTask
.js:21:8)
    at c:\www\bb\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:52:4

    at f (c:\www\bb\node_modules\gulp\node_modules\orchestrator\node_modules\end
-of-stream\node_modules\once\once.js:17:25)
    at DestroyableTransform.onend (c:\www\bb\node_modules\gulp\node_modules\orch
estrator\node_modules\end-of-stream\index.js:31:18)
    at emitNone (events.js:72:20)
    at DestroyableTransform.emit (events.js:166:7)
    at c:\www\bb\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\n
ode_modules\readable-stream\lib\_stream_readable.js:965:16

**Comment by jakemmarsh** [comment]
That issue is related to the `cb` definition you referred to above. It's been fixed in master
