### ISSUE TITLE
Error: SourceMapGenerator.prototype.applySourceMap requires either an explicit source file, or the source map's "file" property. 

### ISSUE THREAD

**Issue by mnemanja** [jakemmarsh/angularjs-gulp-browserify-boilerplate#126]
Hi guys, 
After this https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/pull/124 I've started getting this error.

    07 12 2015 11:29:58.524:ERROR [karma]: [Error:     SourceMapGenerator.prototype.applySourceMap requires either an explicit source file, or the     source map's "file" property. Both were omitted.]
    Error: SourceMapGenerator.prototype.applySourceMap requires either an explicit source file, or the source map's "file" property. Both were omitted.
        at SourceMapGenerator_applySourceMap [as applySourceMap] (...\node_modules\browserify-    ngannotate\node_modules\ng-annotate\node_modules\source-map\lib\source-map\source-map-    generator.js:175:17)
        at SourceMapper.applySourceMap (...\node_modules\browserify-    ngannotate\node_modules\ng-annotate\build\es5\generate-sourcemap.js:92:20)
        at generateSourcemap (...\node_modules\browserify-ngannotate\node_modules\ng-    annotate\build\es5\generate-sourcemap.js:115:20)
        at ngAnnotate (...\node_modules\browserify-ngannotate\node_modules\ng-    annotate\build\es5\ng-annotate-main.js:1153:9)
        at DestroyableTransform.flush [as _flush] (...\node_modules\browserify-    ngannotate\index.js:45:24)
        at DestroyableTransform.<anonymous> (...\node_modules\browserify-ngannotate\node_modules\through2\node_modules\readable-    stream\lib\_stream_transform.js:123:12)
        at DestroyableTransform.g (events.js:260:16)
        at emitNone (events.js:67:13)
        at DestroyableTransform.emit (events.js:166:7)
        at prefinish (...\node_modules\browserify-    ngannotate\node_modules\through2\node_modules\readable-    stream\lib\_stream_writable.js:499:12)
        at finishMaybe (...\node_modules\browserify-    ngannotate\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:507:7)
        at endWritable (...\node_modules\browserify-    ngannotate\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:519:3)
        at DestroyableTransform.Writable.end (...\node_modules\browserify-    ngannotate\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:484:5)
        at DuplexWrapper.onend (...\node_modules\bulkify\node_modules\static-    module\node_modules\duplexer2\node_modules\readable-stream\lib\_stream_readable.js:537:10)
        at DuplexWrapper.g (events.js:260:16)
        at emitNone (events.js:72:20)

**Comment by mnemanja** [comment]
Any way of fixing this?
Thanks

**Comment by mnemanja** [comment]
The `main.js.map` file is being generated, and it's located in the build folder right next to the `main.js`.

For some reason the configuration from the https://github.com/DrewML/angularjs-gulp-browserify-boilerplate/commit/a91fb0ac93a998908aeb87b2d488d277234b4e9c didn't work for me in the manner that the sourcemap file hasn't been generated on the correct path. 

    const sourceMapLocation = global.isProd ? './' : '';

When I've changed it from `''` to `'./'`, as it is for the production, the file got generated.

Although I'm able to generate the sourcemap file, the error still persists.
Do we perhaps need something like this? https://www.npmjs.com/package/karma-sourcemap-loader

**Comment by mnemanja** [comment]
Problem in the karma configuration. Duplicated 'browserify-ngannotate',... Ma bad :)

I'll move the sourceMapLocation problem to the corresponding place.
