### ISSUE TITLE
Gulp Protractor tests passing when it should fail

### ISSUE THREAD

**Issue by karneaud** [jakemmarsh/angularjs-gulp-browserify-boilerplate#177]
Using the default settings that came with the boilerplate I run the following tests

```
'use strict';

describe('E2E: Routes', function() {

  it('should have a working home route', function() {
    browser.get('/enter'); // should fail as there is no such path
    expect(browser.getLocationAbsUrl()).toMatch('/holyshit'); // should fail as there is no such match
  });

  it('should have a title', function(){
    expect(browser.getTitle()).toEqual('Super Calculator'); // should fail as there is no such title
  });

});
```

when running `gulp protractor`

I get the following results

> Starting selenium standalone server...
> [launcher] Running 1 instances of WebDriver
> Selenium standalone server started at http://192.168.0.3:58872/wd/hub
> Started
> ..
>
> 2 specs, 0 failures
> Finished in 0.019 seconds
> Shutting down selenium standalone server.
> [launcher] 0 instance(s) of WebDriver still running
> [launcher] chrome #1 passed
> [15:37:53] Finished 'protractor' after 3.59 s

Is it that I need to run `gulp test` or is there something else I should be looking at as this should have failed

**Comment by jakemmarsh** [comment]
I'm sorry, but it looks like the tests are all passing? It specifically says "2 specs, 0 failures" and "chrome #1 passed"

**Comment by karneaud** [comment]
@jakemmarsh EXACTLY.... it shouldn't. Ran this again directly in node and it failed as expected. Is there something in your script I should be looking at?

**Comment by karneaud** [comment]
did a console.log on browser.getLocationAbsUrl() and got

> { closure_uid_651539774: 173,
>   flow_: 
>    { events_: {},
>      propagateUnhandledRejections_: true,
>      activeQueue_: 
>       { events_: [Object],
>         closure_uid_651539774: 127,
>         name_: 'TaskQueue::127',
>         flow_: [Circular],
>         tasks_: [Object],
>         interrupts_: null,
>         pending_: null,
>         state_: 'new',
>         unhandledRejections_: Set {} },
>      taskQueues_: Set { [Object] },
>      shutdownTask_: null,
>      hold_: 
>       { _called: false,
>         _idleTimeout: 2147483647,
>         _idlePrev: [Object],
>         _idleNext: [Object],
>         _idleStart: 2805,
>         _onTimeout: [Function: wrapper],
>         _repeat: [Function] },
>      closure_uid_651539774: undefined },
>   stack_: null,
>   parent_: 
>    { closure_uid_651539774: 172,
>      flow_: 
>       { events_: {},
>         propagateUnhandledRejections_: true,
>         activeQueue_: [Object],
>         taskQueues_: [Object],
>         shutdownTask_: null,
>         hold_: [Object],
>         closure_uid_651539774: undefined },
>      stack_: { [Task: Protractor.getLocationAbsUrl()] name: 'Task' },
>      parent_: null,
>      callbacks_: [ [Object] ],
>      state_: 'pending',
>      handled_: true,
>      value_: undefined,
>      queue_: null },
>   callbacks_: null,
>   state_: 'pending',
>   handled_: false,
>   value_: undefined,
>   queue_: null }

this seems to return an object rather than a string. I was thinking I should do a .then() on it but this also leads to nothing......

**Comment by karneaud** [comment]
confirming that running protractor on node works

> node node_modules/.bin/protractor test/protractor.conf.js
> Starting selenium standalone server...
> [launcher] Running 1 instances of WebDriver
> Selenium standalone server started at http://192.168.0.3:57745/wd/hub
> Started
> F
> 
> Failures:
> 1) E2E: Routes should fail
>   Message:
>     Expected 'http://localhost:3000/' to equal '/nothing'.
>   Stack:
>     Error: Failed expectation
>         at Object.<anonymous> (routes_spec.js:12:39)
>         at process._tickCallback (node.js:406:9)
> 
> 1 spec, 1 failure
> Finished in 0.495 seconds
> Shutting down selenium standalone server.
> [launcher] 0 instance(s) of WebDriver still running
> [launcher] chrome #1 failed 1 test(s)
> [launcher] overall: 1 failed spec(s)
> [launcher] Process exited with error code 1

**Comment by karneaud** [comment]
When the server starts the browser pops open but the URL in the address bar has a string "data;" not sure if that has anything to do with it also

**Comment by karneaud** [comment]
I'm not sure but 

testServer seems to not starting up. Really been spending more time trying to debug the tests rather than debugging my code here 

:-(

**Comment by karneaud** [comment]
I note you mentioned something here #33 yet in the repo that I installed I am using express....should I be using express?

**Comment by jakemmarsh** [comment]
Oops I'm sorry, misread the original issue up there.

I'm unable to replicate this issue locally. Protractor runs its own Selenium standalone server, so no you shouldn't need to use Express. What package version(s) do you have installed?

**Comment by karneaud** [comment]
Taken from **package.json**

```
"name": "angularjs-gulp-browserify-boilerplate",
  "version": "1.5.6",
  "author": "Jake Marsh <jakemmarsh@gmail.com>",
  "description": "Boilerplate using AngularJS, SASS, Gulp, and Browserify while also utilizing best practices.",
```

**Comment by karneaud** [comment]
I pulled this from your **protractor.js** file

```

gulp.task('protractor', ['prod','webdriver_manager',  'webdriver'], function(cb) {

  const testFiles = gulp.src('test/e2e/**/*.js');

  testServer({
    port: config.testPort,
    dir: config.buildDir
  }).then((server) => {
    console.log('ok server up');
    testFiles.pipe(protractor({
        configFile: config.test.protractor,
        args: ['--baseUrl', config.baseUrl],
        debug:true
    })).on('error', (err) => {
      // Make sure failed tests cause gulp to exit non-zero
      throw err;
    }).on('end', () => server.close(cb));
  });

});
```

I noted in #33 there was a discussion about the use of the expressjs server. Why do I have the feeling I have been using the wrong repo :/

**Comment by jakemmarsh** [comment]
I'm not sure why this would be related to the Express server.

What actual version of protractor do you have installed?

**Comment by karneaud** [comment]
@jakemmarsh the version installed via your package is 2.5.1. Well I'm not sure why either but like I said...If I run this in **node** rather than **gulp** it works as expected. The outputs results while running in gulp are very "unexpected"...I'm not as proficient with protractor so I'm not sure what to look for

**Comment by karneaud** [comment]
anything?

**Comment by worldspawn** [comment]
I am having this exact same issue. Anytime an `expect` refers to a protractor promise (browser.getTitle() for example returns a promise) it doesn't seem to wait for it. The test does execute (console.log('junk') confirmed it) and non promise based assertions behave as expected (eg. expect('foo').toEqual('bar') will fail the test).

If protractor is run directly it works. If run through gulp-protractor it fails.

config:
```
exports.config = {
  //seleniumAddress: 'http://localhost:4444/wd/hub',
  seleniumServerJar: './node_modules/protractor/selenium/selenium-server-standalone-2.52.0.jar',
  //specs: ['todo-spec.js'],
  chromeDriver: './node_modules/protractor/selenium/chromedriver_2.21.exe',
  //directConnect: true,
  //framework: 'jasmine'
};
```

task

```
var gulp = require('gulp');
var protractor = require("gulp-protractor").protractor;

gulp.task('default', function () {
  gulp.src(["./*.spec.js"])
    .pipe(protractor({
        configFile: "./conf.js",
        //args: ['--baseUrl', 'http://127.0.0.1:8000']
    }))
    .on('error', function(e) { throw e })
});
```

test (take from protractor help docs)

```
describe('angularjs homepage todo list', function() {
  it('should add a todo', function() {
    browser.get('https://angularjs.org');

    element(by.model('todoList.todoText')).sendKeys('write first protractor test');
    element(by.css('[value="add"]')).click();

    var todoList = element.all(by.repeater('todo in todoList.todos'));
    expect(todoList.count()).toEqual(3);
    expect(todoList.get(2).getText()).toEqual('write first protractor test');

    // You wrote your first test, cross it off the list
    todoList.get(2).element(by.css('input')).click();
    var completedAmount = element.all(by.css('.done-true'));
    expect(completedAmount.count()).toEqual(2);
    
  });
});

```

**Comment by worldspawn** [comment]
Update: I can reproduce this when i run what gulp protractor runs...

`C:\Users\critc\source\protractor-test\node_modules\gulp-protractor\node_modules\.bin\protractor.cmd ./conf.js --specs ./test.spec.js`

That fails the same way. If you modify the protractor.cmd file under gulp-protractor to not use it's dependency but the parent one (the one you installed with npm install protractor) the tests run.

So node  "%~dp0\..\..\..\protractor\bin\protractor" %* 
instead of
node  "%~dp0\..\protractor\bin\protractor" %*

not sure why...

**Comment by worldspawn** [comment]
I went into my gulp-protractor module folder and bumped the protractor dependency to ^3.2.1 and now it works @karneaud 

So i think the short answer is that 3.1.1 version of protractor is a bit broken? or the chrome driver/selenium it uses is.

**Comment by worldspawn** [comment]
Ok i blew away my node modules folder. I removed my dependency on protractor so I had only a dependency on gulp-protractor. I then rewrote my gulp file like so:

``` js
var gulp = require('gulp');
var protractor = require("gulp-protractor").protractor;
var webdriver_update = require('gulp-protractor').webdriver_update;

gulp.task('default', function (cb) {
  webdriver_update(function () {
    gulp.src(["./*.spec.js"])
      .pipe(protractor({
          configFile: "./conf.js",
          //args: ['--baseUrl', 'http://127.0.0.1:8000']
      }))
      .on('error', function(e) { throw e })
      .on('end', function() { cb(); })
  });
});
```

**Comment by karneaud** [comment]
hmmmm @worldspawn thanks for your insight. Will look into it and let you know. I think this boilerplate is a very well organised project compared. These test setup was disappointing for the most part. Glad to see there is still hope for it. Thanks for your help.

**Comment by karneaud** [comment]
@worldspawn i think you are right....just updated the gulp-protractor's protractor dependency to 3.2.1, updated the web drivers and it worked.

**Comment by jakemmarsh** [comment]
I've actually previously removed the explicit dependency on Protractor in a previous update @worldspawn, but glad you got that working. Does that configuration work out of the box, or does it also require manually updating `gulp-protractor`'s protractor dependency?

If the issue is within `gulp-protractor`, unfortunately there's not much that can be done from within this boilerplate. Will need to open an issue (and/or put out a fix) in their repo

**Comment by worldspawn** [comment]
Yes i just followed a link from another issue to here. I'm not using the boilerplate. I removed the explicit dependency (and cleaned up) and thats what got it working, updating the the dependencies from within the gulp-protractor module did work but is not the way to fix this properly.
