### ISSUE TITLE
Failed to load external module babel/register

### ISSUE THREAD

**Issue by huguangju** [jakemmarsh/angularjs-gulp-browserify-boilerplate#181]
run with `gulp dev`, but reported fellow error:
```
[18:50:24] Failed to load external module babel/register
/Users/hugo/programming/github/angular-resources/angularjs-gulp-browserify-boilerplate/gulp/index.js:3
import fs          from 'fs';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/hugo/programming/github/angular-resources/angularjs-gulp-browserify-boilerplate/gulpfile.babel.js:14:1)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
```
run `gulp -v`
```
18:53:32] Failed to load external module babel/register
[18:53:32] CLI version 3.9.0
[18:53:32] Local version 3.9.1
```

**Comment by mnemanja** [comment]
Try deleting the `node_modules`, and then run the `npm install`. I've experienced this, and solved it this way.
Hope it helps you as well.

**Comment by huguangju** [comment]
Thanks a lot. After update to the latest version using `npm i -g gulp`, it worked!
```
[10:05:44] Requiring external module babel-register
[10:05:44] CLI version 3.9.1
[10:05:44] Local version 3.9.1
```

**Comment by mnemanja** [comment]
I can confirm that that's also the version that I'm using. 

Cheers
