### ISSUE TITLE
npm run build throws "CssSyntaxError: RightCurlyBracket is expected"

### ISSUE THREAD

**Issue by Janjuks** [jakemmarsh/angularjs-gulp-browserify-boilerplate#210]
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

    at parseError (PATH_TO_PROJECT\node_modules\csso\lib\parser\index.js:46:17)
    at eat (PATH_TO_PROJECT\node_modules\csso\lib\parser\index.js:77:5)
    at getBlockWithBrackets (PATH_TO_PROJECT\node_modules\csso\lib\parser\index.js:515:5)
    at getRuleset (PATH_TO_PROJECT\node_modules\csso\lib\parser\index.js:315:16)
    at Object.getStylesheet [as stylesheet] (PATH_TO_PROJECT\node_modules\csso\lib\parser\index.js:173:25)
    at parse (PATH_TO_PROJECT\node_modules\csso\lib\parser\index.js:1849:34)
    at minify (PATH_TO_PROJECT\node_modules\csso\lib\index.js:69:9)
    at Object.minifyStylesheet [as minify] (PATH_TO_PROJECT\node_modules\csso\lib\index.js:100:12)
    at Object.exports.fn (PATH_TO_PROJECT\node_modules\svgo\plugins\minifyStyles.js:30:45)
    at PATH_TO_PROJECT\node_modules\svgo\lib\svgo\plugins.js:59:45
    at Array.filter (native)
    at monkeys (PATH_TO_PROJECT\node_modules\svgo\lib\svgo\plugins.js:46:39)
    at PATH_TO_PROJECT\node_modules\svgo\lib\svgo\plugins.js:66:17
    at Array.filter (native)
    at monkeys (PATH_TO_PROJECT\node_modules\svgo\lib\svgo\plugins.js:46:39)
    at PATH_TO_PROJECT\node_modules\svgo\lib\svgo\plugins.js:66:17
```

I went through all styles and couldn't find the missing bracket. Not really sure if this is issue related to this project or some other node module, or it's really my styles. Could you atleast help me debug it? Not sure where to start...

**Comment by jakemmarsh** [comment]
Can you show the styles that are causing the error? This stack trace isn't all that helpful otherwise.

It does look like the issue is in either the node_module `csso` or `svgo`, neither of which are in this boilerplate by default.

**Comment by Janjuks** [comment]
`gulp-imagemin@2.4.0`>`imagemin@4.0.0`>`imagemin-svgo@4.2.1`>`is-svg@1.1.1`>`svgo@0.6.6`>`csso@2.0.0`
I can't show the styles at the moment. Later. But you can see that `csso` and `svgo` is one of dependencies.

**Comment by Janjuks** [comment]
Problem was `svgo`. We had `svg` images in `app/images`.
Commented out line 12 in `gulp/tasks/images` for the moment. 
The most annoying thing was that the error said it was `CssSyntaxError`.
