### ISSUE TITLE
Running gulp unit results in ERROR[config]: Invalid config file! when starting Karma server

### ISSUE THREAD

**Issue by deowk** [jakemmarsh/angularjs-gulp-browserify-boilerplate#36]
I am running this on Ubuntu 14.04 with Vagrant

I have done npm install and I see the 'isparta' folder and executable in /bin in the node-modules folder but when I run gulp unit I get the following error.

Starting Karma server...
ERROR [config]: Invalid config file!
  Error: Cannot find module 'isparta'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/vagrant/templatebuilder/test/karma.conf.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

/home/vagrant/templatebuilder/gulp/tasks/unit.js:18
      throw err;
            ^
Error in plugin 'gulp-karma'
karma exited with code 1
    at done (/home/vagrant/templatebuilder/node_modules/gulp-karma/index.js:56:30)
    at ChildProcess.<anonymous> (/home/vagrant/templatebuilder/node_modules/gulp-karma/index.js:82:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:797:12)
vagrant@vagrant-ubuntu-trusty-64:~/templatebuilder$

**Comment by jakemmarsh** [comment]
Looks like there was an issue with Isparta missing its `lib` directory unless installed via NPM ([issue here](https://github.com/douglasduteil/isparta/issues/33)). Fixed in eb58f57c0cf92c5b2ee9a61800b192ec0b187c9c
