### ISSUE TITLE
Gulp dev fails many times without showing any errors 

### ISSUE THREAD

**Issue by maisnamraju** [jakemmarsh/angularjs-gulp-browserify-boilerplate#43]
I get this error quite a lot when i run gulp dev. I have not changed any configurations or anything and I have cleared cache and run npm install but this happens quite often and then all goes back to normal. I have even tried killing all processes that run on port.

 Rebundle...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: watch ENOSPC
  at exports._errnoException (util.js:746:11)
  at FSWatcher.start (fs.js:1172:11)
  at Object.fs.watch (fs.js:1198:11)
  at createFsWatchInstance (/home/kseguy/Desktop/angularjs/node_modules/watchify/node_modules/chokidar/lib/nodefs-handler.js:24:15)
  at setFsWatchListener (/home/kseguy/Desktop/angularjs/node_modules/watchify/node_modules/chokidar/lib/nodefs-handler.js:47:19)
  at EventEmitter.NodeFsHandler._watchWithNodeFs (/home/kseguy/Desktop/angularjs/node_modules/watchify/node_modules/chokidar/lib/nodefs-handler.js:177:15)
  at EventEmitter.NodeFsHandler._handleFile (/home/kseguy/Desktop/angularjs/node_modules/watchify/node_modules/chokidar/lib/nodefs-handler.js:201:8)
  at EventEmitter.<anonymous> (/home/kseguy/Desktop/angularjs/node_modules/watchify/node_modules/chokidar/lib/nodefs-handler.js:353:12)
  at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by jakemmarsh** [comment]
Is this happening to you with a fresh clone/install, or after you've added all your files? I've never personally encountered this error, but from some brief research it looks to be a problem with attempting to watch too many files.

**Comment by maisnamraju** [comment]
Yeah, that was the problem. My machine couldnt handle that many files.

**Comment by jakemmarsh** [comment]
Glad you figured it out! :+1:
